# Generated by Django 5.0.2 on 2025-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_name',
        ),
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
    ]
